#!/bin/bash
# diskhogs -- инструмент анализа расходования дискового пространства для Unix;
# предполагается, что все учетные записи рядовых пользователей
# имеют числовые идентификаторы UID >= 100.
# Рассылает электронные письма с предупреждением всем нарушителям
# и выводит на экран общий отчет.

MAXDISKUSAGE=500
violators="/tmp/diskhogs0.$$"
trap "$(which rm) -f $violators" 0
for name in $(cut -d: -f1,3 /etc/passwd | awk -F: '$2 > 99 { print $1 }')
do
    /bin/echo -n "$name "
    # Вам может потребоваться изменить следующий список каталогов, чтобы
    # он лучше соответствовал структуре каталогов на вашем диске.
    # Наиболее вероятно, что вам придется заменить имя /Users на /home.

    find / /usr /var /Users -xdev -user $name -type f -ls | \
        awk '{ sum += $7 } END { print sum / (1024*1024) }'
done | awk "\$2 > $MAXDISKUSAGE { print \$0 }" > $violators

if [ ! -s $violators ] ; then
    echo "No users exceed the disk quota of ${MAXDISKUSAGE}MB"
    cat $violators
    exit 0
fi
while read account usage ; do

cat << EOF | fmt | mail -s "Warning: $account Exceeds Quota" $account
    Your disk usage is ${usage}MB, but you have been allocated only
    ${MAXDISKUSAGE}MB. This means that you need to delete some of your
    files, compress your files (see 'gzip' or 'bzip2' for powerful and
    easy-to-use compression programs), or talk with us about increasing
    your disk allocation.
    
    Thanks for your cooperation in this matter.
    Your friendly neighborhood sysadmin
EOF
    echo "Account $account has $usage MB of disk space. User notified."

done < $violators

exit 0
