#!/bin/bash

# findsuid -- проверяет доступность для записи всех файлов программ
# с установленным атрибутом SUID и выводит их список в удобном формате.

mtime="7" # Как далеко назад (в днях) проверять время модификации.
verbose=0 # По умолчанию, давайте будем немногословными.

if [ "$1" = "-v" ] ; then
    verbose=1 # Пользователь вызвал findsuid -v, включаем подробный режим.
fi

# find -perm отыскивает файлы с заданными разрешениями: 4000 и выше
# -- это setuid/setgid.

find / -type f -perm +4000 -print0 | while read -d '' -r match
do
    if [ -x "$match" ] ; then

        # Выделить атрибуты владения и привилегий из вывода ls -ld.
        owner="$(ls -ld $match | awk '{print $3}')"
        perms="$(ls -ld $match | cut -c5-10 | grep 'w')"

        if [ ! -z $perms ] ; then
            echo "**** $match (writeable and setuid $owner)"
        elif [ ! -z $(find $match -mtime -$mtime -print) ] ; then
            echo "**** $match (modified within $mtime days and setuid $owner)"
        elif [ $verbose -eq 1 ] ; then
            # По умолчанию перечисляются только опасные сценарии.
            # Если включен подробный режим, выводить все.
            lastmod="$(ls -ld $match | awk '{print $6, $7, $8}')"
            echo " $match (setuid $owner, last modified $lastmod)"
        fi
    fi
done
exit 0
