#!/bin/bash

# fmt -- утилита форматирования текста, действующая как обертка для nroff
# Добавляет два флага: -w X, для задания ширины строк,
# и -h, для расстановки переносов и улучшения выравнивания

while getopts "hw:" opt; do
    case $opt in
        h ) hyph=1              ;;
        w ) width="$OPTARG"     ;;
    esac
done
shift $(($OPTIND - 1))
nroff << EOF
.ll ${width:-72}
.na
.hy ${hyph:-0}
.pl 1
$(cat "$@")
EOF

exit 0
