#!/bin/bash
# fquota -- инструмент анализа расходования дискового пространства для Unix;
# предполагается, что все учетные записи рядовых пользователей
# имеют числовые идентификаторы UID >= 100

MAXDISKUSAGE=20000 # В мегабайтах

for name in $(cut -d: -f1,3 /etc/passwd | awk -F: '$2 > 99 {print $1}')
do
    /bin/echo -n "User $name exceeds disk quota. Disk usage is: "
    # Вам может потребоваться изменить следующий список каталогов, чтобы
    # он лучше соответствовал структуре каталогов на вашем диске.
    # Наиболее вероятно, что вам придется заменить имя /Users на /home.
    find / /usr /var /Users -xdev -user $name -type f -ls | \
        awk '{ sum += $7 } END { print sum / (1024*1024) " Mbytes" }'
    done | awk "\$9 > $MAXDISKUSAGE { print \$0 }"

exit 0
