#!/bin/bash

# getdope -- загружает последнюю колонку "The Straight Dope."
# Настройте ежедневный запуск сценария из cron, если вам это интересно.

now="$(date +%y%m%d)"
start="http://www.straightdope.com/ "
to="testing@yourdomain.com" # Замените нужным адресом.

# Для начала получить URL текущей колонки.

URL="$(curl -s "$start" | \
grep -A1 'teaser' | sed -n '2p' | \
cut -d\" -f2 | cut -d\" -f1)"

# Теперь, вооружившись этими данными, отправим электронное письмо.

( cat << EOF
Subject: The Straight Dope for $(date "+%A, %d %B, %Y")
From: Cecil Adams <dont@reply.com>
Content-type: text/html
To: $to

EOF

curl "$URL"
) | /usr/sbin/sendmail -t

exit 0
