#!/bin/bash

# getlinks -- получая URL, возвращает все относительные и абсолютные ссылки.
# Принимает три параметра: -d генерирует первичные домены в каждой ссылке,
# -i выводит список только внутренних ссылок на сайт (то есть на другие
# страницы на том же сайте), и -x выводит список только внешних ссылок
# (в противоположность -i).

if [ $# -eq 0 ] ; then
    echo "Usage: $0 [-d|-i|-x] url" >&2
    echo "-d=domains only, -i=internal refs only, -x=external only" >&2
    exit 1
fi

if [ $# -gt 1 ] ; then
    case "$1" in
        -d) lastcmd="cut -d/ -f3|sort|uniq"
            shift
            ;;
        -r) basedomain="http://$(echo $2 | cut -d/ -f3)/"
            lastcmd="grep \"^$basedomain\"|sed \"s|$basedomain||g\"|sort|uniq"
            shift
            ;;
        -a) basedomain="http://$(echo $2 | cut -d/ -f3)/"
            lastcmd="grep -v \"^$basedomain\"|sort|uniq"
            shift
            ;;
        *) echo "$0: unknown option specified: $1" >&2
           exit 1
    esac
else
    lastcmd="sort|uniq"
fi

lynx -dump "$1"|\
    sed -n '/^References$/,$p'|\
    grep -E '[[:digit:]]+\.'|\
    awk '{print $2}'|\
    cut -d\? -f1|\
    eval $lastcmd

exit 0
