#!/bin/bash
# ANSI-последовательности управления цветом -- используйте эти переменные
#  для управления цветом и форматом выводимого текста.
#  Имена переменных, оканчивающиеся символом 'f’, соответствуют цветам шрифта
#  (foreground), а имена переменных, оканчивающиеся символом 'b’, соответствуют
#  цветам фона (background).

initializeANSI()
{
 esc="\033" # Если эта последовательность не будет работать,
  # введите символ ESC непосредственно.
 
# Цвета шрифта
 blackf="${esc}[30m"; redf="${esc}[31m"; greenf="${esc}[32m"
 yellowf="${esc}[33m" bluef="${esc}[34m"; purplef="${esc}[35m"
 cyanf="${esc}[36m"; whitef="${esc}[37m"


 # Цвета фона
 blackb="${esc}[40m"; redb="${esc}[41m"; greenb="${esc}[42m"
 yellowb="${esc}[43m" blueb="${esc}[44m"; purpleb="${esc}[45m"
 cyanb="${esc}[46m"; whiteb="${esc}[47m"

 # Жирный, наклонный, с подчеркиванием и инверсное отображение
 boldon="${esc}[1m"; boldoff="${esc}[22m"
 italicson="${esc}[3m"; italicsoff="${esc}[23m"
 ulon="${esc}[4m"; uloff="${esc}[24m"
 invon="${esc}[7m"; invoff="${esc}[27m"
 
 reset="${esc} [0m"
}
