#!/bin/bash
# isprime -- получает число и проверяет, является ли оно простым.
# Использует прием, известный как пробное деление: просто перебирает
# числа от 2 до (n/2) и пытается использовать их в качестве делителя,
# проверяя остаток от деления.

counter=2
remainder=1

if [ $# -eq 0 ] ; then
    echo "Usage: isprime NUMBER" >&2
    exit 1
fi

number=$1

# 3 и 2 -- простые числа, 1 -- нет.
if [ $number -lt 2 ] ; then
    echo "No, $number is not a prime"
    exit 0
fi

# Теперь выполним некоторые вычисления.
while [ $counter -le $(expr $number / 2) -a $remainder -ne 0 ]
do
    remainder=$(expr $number % $counter) # '/’ деление, '%' остаток
    # echo " for counter $counter, remainder = $remainder"
    counter=$(expr $counter + 1)
done

if [ $remainder -eq 0 ] ; then
    echo "No, $number is not a prime"
else
    echo "Yes, $number is a prime"
fi
exit 0
