#!/bin/bash

# logrm -- журналирует все операции удаления файлов, если вызывается без флага -s
removelog="/var/log/remove.log"

if [ $# -eq 0 ] ; then
    echo "Usage: $0 [-s] list of files or directories" >&2
    exit 1
fi

if [ "$1" = "-s" ] ; then
    # Запрошена операция без журналирования...
    shift
else
    echo "$(date): ${USER}: $@" >> $removelog
fi

/bin/rm "$@"

exit 0    
