#!/bin/bash
# rolldice -- анализирует количество и тип костей и имитирует их броски.
# Примеры: d6 = один шестигранник
# 2d12 = два двенадцатигранника у каждого
# d4 3d8 2d20 = один четырехгранник, три восьмигранника
# и два двадцатигранника.

rolldie()
{
    dice=$1
    dicecount=1
    sum=0

    # Первый шаг: представить аргумент в формате MdN.

    if [ -z "$(echo $dice | grep 'd')" ] ; then
        quantity=1
        sides=$dice
    else
        quantity=$(echo $dice | cut -dd -f1)
        if [ -z "$quantity" ] ; then # Пользователь указал dN, а не просто N.
            quantity=1
        fi
        sides=$(echo $dice | cut -dd -f2)
    fi

    echo "" ; echo "rolling $quantity $sides-sided die"

    # Бросить кубик...

    while [ $dicecount -le $quantity ] ; do
        roll=$(( ( $RANDOM % $sides ) + 1 ))
        sum=$(( $sum + $roll ))
        echo " roll #$dicecount = $roll"
        dicecount=$(( $dicecount + 1 ))
    done
    echo "I rolled $dice and it added up to $sum"
}

while [ $# -gt 0 ] ; do
    rolldie $1
    sumtotal=$(( $sumtotal + $sum ))
    shift
done

echo ""
echo "In total, all of those dice add up to $sumtotal"
echo ""
exit 0
