#!/bin/bash

# sftpsync -- принимая имя удаленного каталога на сервере sftp, выгружает
# все новые или изменившиеся файлы в удаленную систему. Для синхронизации
# использует файл с отметкой времени и удивительно изобретательно
# подобранным именем .timestamp.

timestamp=".timestamp"
tempfile="/tmp/sftpsync.$$"
count=0

trap "$(which rm) -f $tempfile" 0 1 15 # Удалить временный файл по завершении.

if [ $# -eq 0 ] ; then
    echo "Usage: $0 user@host { remotedir }" >&2
    exit 1
fi

user="$(echo $1 | cut -d@ -f1)"
server="$(echo $1 | cut -d@ -f2)"

if [ $# -gt 1 ] ; then
    echo "cd $2" >> $tempfile
fi

if [ ! -f $timestamp ] ; then
    # Если файл с отметкой времени отсутствует, выгрузить все файлы.
    for filename in *
    do
        if [ -f "$filename" ] ; then
            echo "put -P \"$filename\"" >> $tempfile
            count=$(( $count + 1 ))
       fi
    done
else
    for filename in $(find . -newer $timestamp -type f -print)
    do
        echo "put -P \"$filename\"" >> $tempfile
        count=$(( $count + 1 ))
    done
fi

if [ $count -eq 0 ] ; then
    echo "$0: No files require uploading to $server" >&2
    exit 1
fi

echo "quit" >> $tempfile
echo "Synchronizing: Found $count files in local folder to upload."

if ! sftp -b $tempfile "$user@$server" ; then
echo "Done. All files synchronized up with $server"
touch $timestamp
fi
exit 0
