#!/bin/bash
# startdropbox -- гарантирует выполнение Dropbox в OS X

app="Dropbox.app"
verbose=1

running="$(ps aux | grep -i $app | grep -v grep)"

if [ "$1" = "-s" ] ; then # -s -- немой режим.
    verbose=0
fi

if [ ! -z "$running" ] ; then
    if [ $verbose -eq 1 ] ; then
        echo "$app is running with PID $(echo $running | cut -d\ -f2)"
    fi
else
    if [ $verbose -eq 1 ] ; then
        echo "Launching $app"
    fi
    open -a $app
fi
exit 0
