#!/bin/bash
# states -- игра "Угадай столицу". Требует наличия файла со списком
# штатов и их столиц state.capitals.txt.

db="/usr/lib/games/state.capitals.txt" # Формат: Штат[табуляция]Город.
if [ ! -r "$db" ] ; then
    echo "$0: Can't open $db for reading." >&2
    echo "(get state.capitals.txt" >&2
    echo "save the file as $db and you're ready to play!)" >&2
    exit 1
fi

guesses=0; correct=0; total=0

while [ "$guess" != "quit" ] ; do
    thiskey="$(randomquote $db)"
    # $thiskey -- выбранная строка. Теперь нужно извлечь название штата
    # и города, и затем создать версию названия города со всеми буквами
    # в нижнем регистре для сопоставления.

    state="$(echo $thiskey | cut -d\ -f1 | sed 's/-/ /g')"
    city="$(echo $thiskey | cut -d\ -f2 | sed 's/-/ /g')"
    match="$(echo $city | tr '[:upper:]' '[:lower:]')"

    guess="??" ; total=$(( $total + 1 )) ;
    echo ""
    echo "What city is the capital of $state?"

    # Главный цикл, где все и происходит. Сценарий выполняет его, пока
    # город не будет правильно угадан, или пока пользователь не введет
    # "next", чтобы пропустить штат, или "quit", чтобы завершить игру.

    while [ "$guess" != "$match" -a "$guess" != "next" -a "$guess" != "quit" ]
    do
        /bin/echo -n "Answer: "
        read guess

        if [ "$guess" = "$match" -o "$guess" = "$city" ] ; then
            echo ""
            echo "*** Absolutely correct! Well done! ***"
            correct=$(( $correct + 1 ))
            guess=$match
        elif [ "$guess" = "next" -o "$guess" = "quit" ] ; then
            echo ""
            echo "$city is the capital of $state." # Вы ДОЛЖНЫ это знать :)
        else
            echo "I'm afraid that's not correct."
        fi
    done

done

echo "You got $correct out of $total presented."
exit 0
    
