#!/bin/bash

# suspenduser -- приостанавливает действие учетной записи до неопределенного
#    момента в будущем

homedir="/home" # Местонахождение домашних каталогов пользователей
secs=10         # Пауза в секундах перед выводом пользователя из системы

if [ -z $1 ] ; then
    echo "Usage: $0 account" >&2
    exit 1
elif [ "$(id -un)" != "root" ] ; then
    echo "Error. You must be 'root' to run this command." >&2
    exit 1
fi

echo "Please change the password for account $1 to something new."
passwd $1

# Теперь посмотрим, если пользователь зарегистрирован в системе.
#    выведем его принудительно.

if who|grep "$1" > /dev/null ; then

    for tty in $(who | grep $1 | awk '{print $2}'); do
        
        cat << "EOF" > /dev/$tty

******************************************************************************
URGENT NOTICE FROM THE ADMINISTRATOR:
 This account is being suspended, and you are going to be logged out
in $secs seconds. Please immediately shut down any processes you
have running and log out.

If you have any questions, please contact your supervisor or
Ruslan Sayfullin, Director of Information Technology.
******************************************************************************
EOF
    done

    echo "(Warned $1, now sleeping $secs seconds)"
    
    sleep $secs
    jobs=$(ps -u $1 | cut -d\ -f1)
    kill -s HUP $jobs # Послать сигнал остановки процессам пользователя.
    sleep 1           # Дать одну секунду...

    kill -s KILL $jobs > /dev/null 2>1 # и остановить те, что еще остались.
    
    echo "$1 was logged in. Just logged them out."
fi

# В заключение закрыть домашний каталог от любопытных глаз.
chmod 000 $homedir/$1

echo "Account $1 has been suspended."

exit 0
