#!/bin/bash
# syncdropbox -- синхронизирует заданный набор файлов или указанную
# папку с хранилищем Dropbox. Это достигается путем копирования
# папки в ~/Dropbox или набора файлов в папку sync в Dropbox с последующим
# запуском Dropbox.app, если это необходимо.

name="syncdropbox"
dropbox="$HOME/Dropbox"
sourcedir=""
targetdir="sync" # Целевая папка в Dropbox для отдельных файлов.

# Проверить начальные аргументы.
if [ $# -eq 0 ] ; then
    echo "Usage: $0 [-d source-folder] {file, file, file}" >&2
    exit 1
fi

if [ "$1" = "-d" ] ; then
    sourcedir="$2"
    shift; shift
fi

# Проверка допустимости.

if [ ! -z "$sourcedir" -a $# -ne 0 ] ; then
    echo "$name: You can't specify both a directory and specific files." >&2
    exit 1
fi

if [ ! -z "$sourcedir" ] ; then
    if [ ! -d "$sourcedir" ] ; then
        echo "$name: Please specify a source directory with -d." >&2
        exit 1
    fi
fi


#######################
#### ГЛАВНЫЙ БЛОК
#######################
if [ ! -z "$sourcedir" ] ; then
    if [ -f "$dropbox/$sourcedir" -o -d "$dropbox/$sourcedir" ] ; then
        echo "$name: Specified source directory $sourcedir already exists." >&2
        exit 1
    fi

    echo "Copying contents of $sourcedir to $dropbox..."
    # -a обеспечивает рекурсивное копирование с сохранением
    # информации о владельце и пр.
    cp -a "$sourcedir" $dropbox
else
    # Исходный каталог отсутствует, поэтому переходим к отдельным файлам.
    if [ ! -d "$dropbox/$targetdir" ] ; then
        mkdir "$dropbox/$targetdir"
        if [ $? -ne 0 ] ; then
            echo "$name: Error encountered during mkdir $dropbox/$targetdir." >&2
            exit 1
        fi
    fi
    # Все готово! Скопировать указанные файлы.
    cp -p -v "$@" "$dropbox/$targetdir"
fi

# Теперь запустить приложение Dropbox, если необходимо, чтобы выполнить
# фактическую синхронизацию.
exec startdropbox -s

