#!/bin/bash
# thumbnails -- создает миниатюры из указанных графических файлов,
# точно указанных размеров или не превышающих указанные размеры, когда
# требуется сохранить пропорции.

convargs="-unsharp 0x.5 -resize"
count=0; exact=""; fit=""

usage()
{
    echo "Usage: $0 (-e|-f) thumbnail-size image [image] [image]" >&2
    echo "-e resize to exact dimensions, ignoring original proportions" >&2
    echo "-f fit image into specified dimensions, retaining proportion" >&2
    echo "-s strip EXIF information (make ready for web use)" >&2
    echo " please use WIDTHxHEIGHT for requested size (e.g., 100x100)"
    exit 1
}

#############
## НАЧАЛО ОСНОВНОГО СЦЕНАРИЯ

if [ $# -eq 0 ] ; then
    usage
fi

while getopts "e:f:s" opt; do
    case $opt in
        e ) exact="$OPTARG"; ;;
        f ) fit="$OPTARG";   ;;
        s ) strip="strip";   ;;
        ? ) usage;           ;;
    esac
done
shift $(($OPTIND - 1)) # Употребить все проанализированные аргументы.

rwidth="$(echo $exact $fit | cut -dx -f1)" # Затребованная ширина.
rheight="$(echo $exact $fit | cut -dx -f2)" # Затребованная высота.

for image
do
    width="$(identify -format "%w" "$image")"
    height="$(identify -format "%h" "$image")"

    # Создать миниатюру для изображения $image, с шириной $width и высотой $height
    if [ $width -le $rwidth -a $height -le $rheight ] ; then
        echo "Image $image is already smaller than requested dimensions. Skipped."
    else
        # Сконструировать новое имя файла.
        suffix="$(echo $image | rev | cut -d. -f1 | rev)"
        prefix="$(echo $image | rev | cut -d. -f2- | rev)"
        newname="$prefix-thumb.$suffix"

        # Добавить окончание "!", чтобы игнорировать пропорции, если требуется.
        if [ -z "$fit" ] ; then
            size="$exact!"
            echo "Creating ${rwidth}x${rheight} (exact size) thumb for file $image"
        else
            size="$fit"
            echo "Creating ${rwidth}x${rheight} (max size) thumb for file $image"
        fi
        convert "$image" $strip $convargs "$size" "$newname"
    fi

    count=$(( $count + 1 ))
done

if [ $count -eq 0 ] ; then
    echo "Warning: no images found to process."
fi
`
exit 0
     
