#!/bin/bash
# watermark -- добавляет указанный текст в виде водяных знаков в заданное
# изображение, сохраняя результат в файле с именем image+wm.

wmfile="/tmp/watermark.$$.png"
fontsize="44" # Должен быть начальным аргументом.

trap "$(which rm) -f $wmfile" 0 1 15 # Не оставлять временный файл.

if [ $# -ne 2 ] ; then
    echo "Usage: $(basename $0) imagefile \"watermark text\"" >&2
    exit 1
fi

if [ ! -r "$1" ] ; then
    echo "$(basename $0): Can't read input image $1" >&2
    exit 1
fi

# Для начала получить размеры изображения.
dimensions="$(identify -format "%G" "$1")"

# Создать временный слой для водяного знака.
convert -size $dimensions xc:none -pointsize $fontsize -gravity south \
    -draw "fill black text 1,1 '$2' text 0,0 '$2' fill white text 2,2 '$2'" \
    $wmfile

# Теперь объединить временный слой и исходный файл.
suffix="$(echo $1 | rev | cut -d. -f1 | rev)"
prefix="$(echo $1 | rev | cut -d. -f2- | rev)"
newfilename="$prefix+wm.$suffix"
composite -dissolve 75% -gravity south $wmfile "$1" "$newfilename"
echo "Created new watermarked image file $newfilename."
exit 0
